Feature/save project
premieroctet/openchakra pull request #101
Opened 2020-10-08 10:41 UTC by PierreCrb

Added functionality to be able to save / share an OpenChakra project from the URL ✨

- Creation of the project if no id is specified in the url ✅

- Update of the already existing project if the id is present in the url and the user id is the correct one ✅

- Be able to share your project with the following url: https://openchakra.app/project/:id ✅

Bug 🚫

When a project has just been created, the user is redirected to his project page but this error appears:

`Cannot have two HTML5 backends at the same time.`

When we refresh the page, the bug disappears, I have not managed to fix this bug for the moment 💡

2020-10-26 15:31 UTC, PierreCrb commented
`Cannot have two HTML5 backends at the same time.`

Bug fix ! you can save your project ✅

2020-10-27 09:41 UTC, shinework requested changes

2020-10-27 09:41 UTC, shinework commented on src/components/Header.tsx
> +const Header = ({ id }: any) => {
Can you replace `any` by the right types?

2020-10-27 09:41 UTC, shinework commented on src/components/headerMenu/HeaderMenu.tsx
> +const HeaderMenu = (props: any) => {
Can you replace `any` by the right types?

2020-10-27 09:41 UTC, shinework commented on src/components/headerMenu/SaveMenuItem.tsx
> +const SaveMenuItem = (props: any) => {
Can you replace `any` by the right types?

2020-10-27 09:41 UTC, shinework commented on src/components/headerMenu/SaveMenuItem.tsx
> +    const response = await fetch('http://localhost:3000/api/project/update', {
```suggestion
    const response = await fetch('/api/project/update', {
```

2020-10-27 09:41 UTC, shinework commented on src/components/headerMenu/SaveMenuItem.tsx
> +        userProject.project.map((e: any) => {
Do not use `any` 😉

2020-10-27 09:41 UTC, shinework commented on src/pages/api/project/check.tsx
> +        name: session!.user.name,
Maybe it's safer to fetch the user by his id?

2020-10-27 09:41 UTC, shinework commented on src/pages/api/project/create.tsx
> +        name: session!.user.name,
Same here (id)

2020-10-27 09:41 UTC, shinework commented on src/pages/api/project/index.tsx
> +  const prisma = new PrismaClient({ log: ['query'] })
remove log

2020-10-27 09:41 UTC, shinework commented on src/pages/api/project/update.tsx
> +  const prisma = new PrismaClient({ log: ['query'] })
remove log

2020-10-27 09:41 UTC, shinework commented on src/pages/api/project/index.tsx
> +    await prisma.$disconnect
👍

2020-10-27 09:41 UTC, shinework commented on src/pages/api/user/index.tsx
> +  const prisma = new PrismaClient({ log: ['query'] })
remove :)

2020-10-27 09:41 UTC, shinework commented on src/pages/index.tsx
> +const App = ({ id }: any) => {
Don't use any :)

2020-10-27 09:41 UTC, shinework commented on src/pages/index.tsx
> +      <Header id={id} />
The `id` may not exist no?

2020-10-27 09:41 UTC, shinework commented on src/utils/checkProject.ts
> +  const response = await fetch('http://localhost:3000/api/project/check', {
```suggestion
  const response = await fetch('/api/project/check', {
```

2020-10-27 09:41 UTC, shinework commented on src/utils/checkProject.ts
> +  const response = await fetch('http://localhost:3000/api/project/create', {
```suggestion
  const response = await fetch('/api/project/create', {
```

2020-10-27 12:42 UTC, PierreCrb commented
Adding a spinner for loading if an id is specified in the url to then display the project

![loading](https://user-images.githubusercontent.com/43297207/97303014-1c8c1d80-185a-11eb-8986-55e699141766.gif)

2020-11-03 07:41 UTC, shinework approved these changes

2020-11-03 12:14 UTC, merged