Feature/fork project
premieroctet/openchakra pull request #105
Opened 2020-10-27 15:15 UTC by PierreCrb

![fork project](https://user-images.githubusercontent.com/43297207/97321637-63384280-186f-11eb-9127-2549e17d68eb.gif)

Added the functionality to fork a project that is not linked to the currently logged in user ✅

2020-10-28 17:20 UTC, PierreCrb commented
![Sans titre](https://user-images.githubusercontent.com/43297207/97472422-1ecda500-194a-11eb-8b3b-bf66d93259f7.gif)

Add project name in url ! ✅

2020-11-02 08:09 UTC, shinework requested changes

2020-11-02 08:09 UTC, shinework commented on prisma/migrations/20201028102833/schema.prisma
> +  url = "***"
Please use an env var: 
```
url = env("DATABASE_URL")
```

2020-11-02 08:09 UTC, shinework commented on src/pages/index.tsx
> +        userProject.project.map((e: Project) => {
You can use the some function here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

const userCanEdit = userProject.project.some((e: Project) => (e.id === props.id))

2020-11-02 15:47 UTC, PierreCrb commented
![demo](https://user-images.githubusercontent.com/43297207/97888025-f15a7000-1d2a-11eb-8591-de3c949d6899.gif)

Login / Logout ✅
Clean code ✅
Fix slug url error ✅

2020-11-03 07:41 UTC, shinework approved these changes

2020-11-03 12:14 UTC, merged